service: lambda-function-datadog

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1

functions:
  lambdaFunction:
    handler: lambda_function.lambda_handler
    environment:
      DD_API_KEY: ${env:DD_API_KEY}
      DD_APP_KEY: ${env:DD_APP_KEY}

plugins:
  - serverless-plugin-datadog
