name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Deploy with Serverless
        run: npx serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
          NODE_OPTIONS: '--max-old-space-size=4096'
          AWS_REGION: 'us-east-1'
          AWS_DEFAULT_REGION: 'us-east-1'
          SERVERLESS_DEBUG: 'true'
          SERVERLESS_VERBOSE: 'true'
          SERVERLESS_LOG_LEVEL: 'debug'
          SERVERLESS_DISABLE_CACHE: 'true'
          SERVERLESS_DISABLE_TELEMETRY: 'true'
          SERVERLESS_SERVICE_NAME: 'lambda-function-datadog'
          SERVERLESS_STAGE: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
          SERVERLESS_API_KEY: ${{ secrets.SERVERLESS_API_KEY }}
